name: test deploy

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest
    outputs: 
      message: ${{steps.version.outputs.message}}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Generation message
        id: version
        run: echo "message=Hello depuis build" >> $GITHUB_OUTPUT

  deploy:
     runs-on: ubuntu-latest
     needs: build

     steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: message depuis build
        id: affiche
        run: echo "message ${{needs.build.outputs.message}}"
   

  
