
name: retest deploy

on: [push]

jobs:
  build:
     runs-on: ubuntu-lastest
     outputs:
        version: ${steps.first.outputs.version}

     steps:
      - name: checkout
        uses: actions/checkout@v4
    
      - name: message
        id: first
        run: echo "version=1.0${{GITHUB_RUN_NUMBER}}"
 
  test:
     runs-on: ubuntu-latest
     needs: build
     outputs:
       message: ${{steps.display.outputs.message}}

     steps:
      - name: checkout
        uses: actions/checkout@v4
  
      - name: affiche
        id: display
        run: echo"messag=test reussie" >> $GITHUB_OUTPUTS

  deploy:
     runs-on: ubuntu-latest
     needs: [build,test]

     steps:
      - name: checkout
        uses: actions/checkout@v4
       

      - name: affiche version
        run: echo"${{needs.build.outputs.version}}"
     

  
