
name: retest deploy

on: [push]

jobs:
  build:
     runs-on: ubuntu-latest
     outputs:
        version: ${{steps.first.outputs.version}}

     steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Génération version
        id: first
        run: echo "version=1.0${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
 
  test:
    runs-on: ubuntu-latest
    needs: build
    outputs:
     message: ${{steps.display.outputs.message}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Test réussi
        id: display
        run: echo "message=Test réussi ✅" >> $GITHUB_OUTPUT

  deploy:
     runs-on: ubuntu-latest
     needs: [build,test]

     steps:
      - name: checkout
        uses: actions/checkout@v4
       

      - name: affiche version Et message
        run: |
          echo "La version du build ${{needs.build.outputs.version}}"
          echo "message du test ${{needs.test.outputs.message}}"
          
               

  
