name: Random Gen

on: [push]

jobs:
  random-nums:
    runs-on: ubuntu-latest

    steps:
      - name: generate num
        id: gen
        run: echo "num=$((RANDOM % 100))" >> $GITHUB_OUTPUT

      - name: affiche
        run: echo "Le nombre aléatoire est ${{ steps.gen.outputs.num }}"
    


        


