name: Test & Deploy Laravel App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gen.outputs.version }}   # ✅ "steps" et pas "stpes"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate version
        id: gen
        run: echo "version=1.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT


  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP 8.3
        run: |
          sudo add-apt-repository ppa:ondrej/php -y
          sudo apt update
          sudo apt install -y php8.3

      - name: Run Laravel tests
        run: php artisan test


  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Deploy version
        if: ${{ needs.test.result == 'success' }}    # ✅ les valeurs doivent être entre guillemets
        run: echo "Déploiement de la version ${{ needs.build.outputs.version }}"
  notify:
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ needs.test.result == 'fealure' }}
    steps:
      - run: echo "Le Déploiment a échouer"
        
