name: Test & Deploy Laravel App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gen.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate version
        id: gen
        run: echo "version=1.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT


  test:
    runs-on: ubuntu-latest
    needs: build  # ✅ optionnel, mais logique de dépendance (build avant test)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP 8.3
        run: |
          sudo add-apt-repository ppa:ondrej/php -y
          sudo apt update
          sudo apt install -y php8.3
          php -v   # ✅ vérifie que PHP est bien installé

      - name: Run Laravel tests
        run: php artisan test


  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: ${{ needs.test.result == 'success' }}   # ✅ placé ici, pas au niveau du step

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Deploy version
        run: echo "🚀 Déploiement de la version ${{ needs.build.outputs.version }}"


  notify:
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ needs.test.result == 'failure' }}   # ✅ entre guillemets

    steps:
      - name: Notification d’échec
        run: echo "🚨 Le déploiement a échoué car les tests n'ont pas passé avec succès."
