name: laravel-ci

on: [push]

jobs:
  build:
   runs-on: ubuntu-latest
   outputs:
     version: ${{stpes.gen.outputs.version}}

   steps:
     - name: Checkout
       uses: actions/checkout@v4

     - name: version app
       id: gen
       run: echo "version=1.0${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
  test:
    runs-on: ubuntu-latest
   

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install php8.3
        id: insphp
        run: |
            run sudo add-apt-repository ppa:ondrej/php
            run sudo apt update
            run sudo apt install php8.3

      - name: php artisan test
        id: artitest
        run: echo "php artisan test"
  deploy:
   runs-on: ubuntu-latest
   needs: [build,test]
   steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: deploiment
      if: ${{needs.test.result == success}}
      run: echo " deploiment de la version  ${{needs.build.gen.version}} "
       
        
